import {createSelector, createEntityAdapter } from "@reduxjs/toolkit";
import {apiSlice } from "../../app/api/apiSlice";

// Create an entity adapter for managing disease entities
const diseaseEntityManager = createEntityAdapter({});

// Define the initial state using the entity adapter, if it exict
const initialDiseaseState = diseaseEntityManager.getInitialState();
// Inject endpoints into the apiSlice from the external apiSlice module
export const diseasesApiSlice = apiSlice.injectEndpoints({
    endpoints: builder => ({
        // Define the 'getDiseases' endpoint for fetching diseases
        getDiseases: builder.query({
            query: () => '/diseases', // Endpoint URL
            validateStatus: (response, result) => {
                // Custom status validation function some error return 200 status, so we need to check them both.
                return response.status === 200 && !result.isError;
            },
            transformResponse: responseData => {
                // Transform response data before storing it in the Redux store
                const loadedDiseases = responseData.map(disease => {
                    disease.id = disease._id; // Assign 'id' property to disease object
                    return disease;
                });
                return diseaseEntityManager.setAll(initialDiseaseState, loadedDiseases); // Update state with transformed data
            },
            providesTags: (result, error, arg) => {
                // Provide tags for caching purposes
                if (result?.ids) {
                    return [
                        { type: 'Disease', id: 'LIST' },
                        ...result.ids.map(id => ({ type: 'Disease', id }))
                    ];
                } else return [{ type: 'Disease', id: 'LIST' }];
            }
        }),
    }),
});

// Export query hooks generated by the apiSlice
export const {
    useGetDiseasesQuery,
} = diseasesApiSlice;

// Select the query result object from the getDiseases endpoints
export const selectDiseasesResult = diseasesApiSlice.endpoints.getDiseases.select();

// Create a memoized selector to extract diseases data from the query result
const selectDiseasesData = createSelector(
    selectDiseasesResult,
    diseasesResult => diseasesResult.data // normalized state object with ids & entities
);

// Extract selectors using the entity adapter's getSelectors function
// Pass in a selector that returns the diseases slice of state
export const {
    selectAll: selectAllDiseases,
    selectById: selectDiseaseById,
    selectIds: selectDiseaseIds
} = diseaseEntityManager.getSelectors(state => selectDiseasesData(state) ?? initialDiseaseState);
